### ISSUE TITLE
Question about intended use

### ISSUE THREAD

**Issue by lonix1** [iulian-radu-at/sharable-kanban-boards#1]
@iulian-radu-at Thanks for this very nice and extremely professional extension!

It goes into source control, so it will only be updated for others when you push your branch and they pull it. So changes are not real time.

It would be good for managing your own work, but that would go into source control too, and be seen by others (unless you add your board to a .gitignore).

I was wondering how you personally use it in your workflow? Any tips for how best to use it?

**Comment by iulianraduat** [comment]
Hi @lonix1 ,

This plugin was thought to be used in a team environment and to be a replacement for tools like Jira.
The advantage of using this plugin is that the need for someone to setup and maintain a remote environment disappears. Also the licensing fees are gone.

I do not think that being "real time" is critical for this kind of tools. The way I see the workflow is that different people works on different tasks and then they have regular meetings to align as a team. As such, the updated status of the tickets is necessary mostly at these times. Until then, anyone can still see the "starting" status for these tickets. Also, any time one wants to let the team to see an updated status, one can push the updated board into remote repo.

If you want to use it for your own then your solution is good, but the condition is that all people committing code to that branch to use it in a private mode. As long as one will push it to the branch, there will be a "conflict" between the pushed one and the locally one.

Another solution is to have your own project where you create the board and so you do not need to push it to any remote repo.

Feel free to ask more, or if you are happy with this answer to close this "issue" 😃 

Cheers,
Iulian

**Comment by lonix1** [comment]
Thanks!

Another point:
For personal work, it would be nice to be able to choose where to save the config. Right now it's save to workspace settings (`.vscode/sharable-kanban-boards.json`). If I could change the location, I could choose user settings, and then it wouldn't be committed to source control. A feature addition for the future maybe?
